---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: ops-files
- name: runtime-ci
- name: bosh-io-release
- name: compiled-release-tarball
- name: stemcell

outputs:
- name: updated-compiled-releases-ops-file

run:
  path: runtime-ci/tasks/update-compiled-release-ops/task

params:
  RELEASE_NAME:
