---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: ops-files
- name: windows-stemcell

outputs:
- name: updated-stemcell-ops-file
- name: commit-message

run:
  path: runtime-ci/tasks/update-windows-stemcell-ops/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  ORIGINAL_WINDOWS_OPS_FILE_PATH: operations/windows-cell.yml
  UPDATED_WINDOWS_OPS_FILE_PATH: windows-cell.yml
