---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
- name: deployment-configuration
- name: release
- name: stemcell

outputs:
- name: commit-message
- name: updated-deployment-manifest
- name: updated-ops-file

run:
  path: runtime-ci/tasks/update-single-release/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  ORIGINAL_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  UPDATED_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  RELEASE_NAME: 
  TARGET: manifest
  ORIGINAL_OPS_FILE_PATH:
  UPDATED_OPS_FILE_PATH:
